// <auto-generated />
namespace Job_Offers_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addJobModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addJobModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202211240436464_addJobModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
